name: iMPCAT-SAFE
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy = 1.21.5
  - matplotlib = 3.5.1
  - ipywidgets = 7.6.5
  - scipy = 1.7.3
  - numba = 0.55.1
  - pandas = 1.3.5
  - rasterio = 1.2.10
